#!/usr/bin/env python3
"""Generate topology/simple.net (ibsim netfile format).

Usage: scripts/gen-simple-net.py > topology/simple.net

GUID convention (readable at a glance; ibsim sets HCA port GUID = node GUID + 1):
  switches  0x0002c90000000N00   (SW01=...100, SW02=...200)
  HCAs      0x0002c900000000N0   (HCA01=...10, HCA02=...20 ...), port GUID = node GUID + 1
"""
sw = {"SW01": 0x0002c90000000100, "SW02": 0x0002c90000000200}
ca = {f"HCA0{i}": 0x0002c90000000000 + i * 0x10 for i in range(1, 5)}
# (nodeA, portA, nodeB, portB)
links = [("SW01", 1, "HCA01", 1), ("SW01", 2, "HCA02", 1), ("SW01", 3, "SW02", 3),
         ("SW02", 1, "HCA03", 1), ("SW02", 2, "HCA04", 1)]
nodes = {**{n: ("S", g) for n, g in sw.items()}, **{n: ("H", g) for n, g in ca.items()}}
adj = {}
for a, pa, b, pb in links:
    adj[(a, pa)] = (b, pb)
    adj[(b, pb)] = (a, pa)
out = ["# simple.net - generated by scripts/gen-simple-net.py (ibsim netfile format).",
       "#   HCA01 -[1]SW01[3]---[3]SW02[1]- HCA03",
       "#   HCA02 -[2]SW01        SW02[2]- HCA04", ""]
for name, (kind, g) in nodes.items():
    hx = f"0x{g:016x}"
    if kind == "S":
        out += ["vendid=0x2c9", "devid=0xd2f0", f"sysimgguid={hx}", f"switchguid={hx}({hx[2:]})",
                f'Switch 8 "S-{g:016x}"\t# "{name}" base port 0 lid 0 lmc 0']
    else:
        out += ["vendid=0x2c9", "devid=0x1017", f"sysimgguid={hx}", f"caguid={hx}",
                f'Ca 1 "H-{g:016x}"\t# "{name}"']
    for p in range(1, 9 if kind == "S" else 2):
        if (name, p) in adj:
            rn, rp = adj[(name, p)]
            rk, rg = nodes[rn]
            out.append(f'[{p}]\t"{rk}-{rg:016x}"[{rp}]\t# "{rn}" lid 0 4xQDR')
    out.append("")
print("\n".join(out))
